# Generated by Django 4.2.7 on 2024-04-23 11:42

from django.db import migrations
from django.contrib.auth.models import Permission, User, Group
from django.contrib.contenttypes.models import ContentType


def create_social_group_with_perm(apps, schema_editor):
    social_group = Group.objects.filter(name='social')
    # if there is social group with social_auth perm then return
    if len(social_group):
        if len(social_group.permissions.filter(codename='social_auth')):
            return

    if not len(social_group):
        social_group = Group.objects.create(name='social')
    social_perm = Permission.objects.filter(codename='social_auth')
    if not len(social_perm):
        content_type = ContentType.objects.get_for_model(User)
        social_perm = Permission.objects.create(
            codename='social_auth',
            name='Social Auth',
            content_type=content_type
        )
    social_group.first().permissions.add(social_perm.first())
    social_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.RunPython(create_social_group_with_perm),
    ]
