version: "3.9"
services:
  postgres_svc:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  django_svc:
    image: django:latest
    container_name: django
    depends_on:
      - postgres_svc
    volumes:
      - static_volume:/shop/static
      - media_volume:/shop/media
    env_file:
      - .env
    command: bash -c "chmod +x manage.py  && ./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 app.wsgi"
  nginx_svc:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx
    image: nginx
    volumes:
      - static_volume:/shop/static
      - media_volume:/shop/media
    depends_on:
      - django_svc
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
