# Generated by Django 4.2.7 on 2024-04-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
            ],
        ),
    ]
