# Generated by Django 4.2.7 on 2024-04-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_timestamp',), 'verbose_name': 'cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
