# Generated by Django 4.2.7 on 2024-04-07 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('delivery_method', models.BooleanField(choices=[(False, 'Delivery'), (True, 'Self pickup')], default=0, verbose_name='Delivery method')),
                ('delivery_address', models.CharField(max_length=300)),
                ('payment_method', models.BooleanField(choices=[(False, 'By card'), (True, 'By cash')], default=0, verbose_name='Payment method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
