# Generated by Django 4.2.7 on 2024-04-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem_delete_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'sold item', 'verbose_name_plural': 'Sold items'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='payment_on_get',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
